server:
  port: ${PORT:8080}

app:
  token:
    secret-key: ${JWT_SECRET_KEY:Y3Vyc29fYXV0aF9hcGktc3RhdGVsZXNzLWphdmEtYXBwLWRhbi1tYXJ6by1naWw=}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/auth-db
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    initialization-mode: always
    initialize: true
    continue-on-error: true
    platform: postgresql
    maxActive: 3
  jpa:
    hibernate:
      ddl-auto: create-drop
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect