version: '1'

services:
  stateless-auth-db:
    container_name: stateless-auth-db
    image: postgres:latest
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - auth
    ports:
      - "5432:5432"
  statefull-auth-db:
    container_name: statefull-auth-db
    image: postgres:latest
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - auth
    ports:
      - "5433:5432"
  token-redis:
    container_name: token-redis
    image: redis:latest
    networks:
      - auth
    ports:
      - "6379:6379"
  stateless-auth-api:
    build: './stateless/stateless-auth-api'
    container_name: stateless-auth-api
    depends_on:
      - stateless-auth-db
    environment:
      - PORT=8080
      - DB_HOST=stateless-auth-db
      - DB_PORT=5432
      - DB_NAME=auth-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET_KEY=Y3Vyc29fYXV0aF9hcGktc3RhdGVsZXNzLWphdmEtYXBwLWRhbi1tYXJ6by1naWwtQ09OVEFJTkVS
    networks:
      - auth
    ports:
      - "8080:8080"
  stateless-any-api:
    build: './stateless/stateless-any-api'
    container_name: stateless-any-api
    environment:
      - PORT=8081
      - JWT_SECRET_KEY=Y3Vyc29fYXV0aF9hcGktc3RhdGVsZXNzLWphdmEtYXBwLWRhbi1tYXJ6by1naWwtQ09OVEFJTkVS
    networks:
      - auth
    ports:
      - "8081:8081"
  statefull-auth-api:
    build: './statefull/statefull-auth-api'
    container_name: statefull-auth-api
    depends_on:
      - statefull-auth-db
    environment:
      - PORT=8082
      - DB_HOST=statefull-auth-db
      - DB_PORT=5432
      - DB_NAME=auth-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_HOST=token-redis
      - REDIS_PORT=6379
    networks:
      - auth
    ports:
      - "8082:8082"
  statefull-any-api:
    build: './statefull/statefull-any-api'
    container_name: statefull-any-api
    environment:
      - PORT=8083
      - STATEFUL_AUTH_BASE=http://statefull-auth-api:8082
    networks:
      - auth
    ports:
      - "8083:8083"
networks:
  auth:
    driver: bridge